s|%CommandLine%|{process.command_line}|g
s|%community_id%|{network.community_id}|g
s|%CurrentDirectory%|{event_data.process.working_directory}|g
s|%document_id%|{soc_id}|g
s|%dns.query.name%|{dns.query.name}|g
s|%hostname%|{event_data.host.name}|g
s|%Image%|{process.executable}|g
s|%ImageLoaded%|{dll.name}|g
s|%ParentImage%|{process.parent.executable}|g
s|%ParentProcessGuid%|{ParentProcessGuid}|g
s|%private_ip%|{network.private.ip}|g
s|%ProcessGuid%|{event_data.process.entity_id}|g
s|%public_ip%|{network.public.ip}|g
s|%related.hosts%|{event_data.related.hosts}|g
s|%related_ip%|{event_data.related.ip}|g
s|%src_ip%|{source.ip}|g
s|%dst_ip%|{destination.ip}|g
s|%User%|{user.name}|g
s/|expand:/:/g
