name: Security Onion - Grid Node Login Failure (SSH)
id: 1b2d75fb-b82c-4d2f-9596-0313ad8dc761
description: |
    Detects when a user fails to login to a grid node via SSH. Review associated logs for username and source IP.
type: detection
detection_id: '923421c7-9b1e-45d4-80cc-e21d060c8723'
detection_category: ''
detection_type: 'sigma'
contributors:
  - 'SecurityOnionSolutions'
created: 3/24/2025
modified: 3/25/2025
questions:
  - question: "What user failed to login?"
    context: "This is the username that attempted and failed to authenticate via SSH to the grid node. Is it a known user?"
    answer_sources:
        - linux_auth
    query: |
        aggregation: false
        logsource:
            product: alert
        detection:
            selection:
                document_id|expand: '%document_id%'
            condition: selection
        fields:
            - event_data.user.name
    example_query_output: '2025-03-18 11:06:28.301 -04:00 | sysadmin'
  - question: "What IP did the failed login come from?"
    context: "This is the source IP address that attempted to authenticate via SSH and failed."
    answer_sources:
        - linux_auth
    query: |
        aggregation: false
        logsource:
            product: alert
        detection:
            selection:
                document_id|expand: '%document_id%'
            condition: selection
        fields:
            - event_data.source.ip
    example_query_output: '2025-03-18 11:06:28.301 -04:00 | 192.168.55.6'
  - question: "What source IP do login attempts for this user normally come from?"
    context: "Do the failed login attempts come from the same IP/s?"
    answer_sources:
        - linux_auth
    range: -30d
    query: |
        aggregation: true
        logsource:
            product: linux
            service: auth
        detection:
            selection:
                event.action: ssh_login
                tags|contains: so-grid-node
                User|expand: '%User%'
            condition: selection
        fields:
            - source.ip
            - event.outcome
    example_query_output: '2 | 192.168.55.6 | failed'
  - question: "Are there any other failed SSH logins on any Grid Nodes?"
    context: "Check for any additional failed SSH login attempts across all Grid Nodes in the last 30 days. This will help identify any patterns or trends in failed login attempts."
    answer_sources:
        - linux_auth
    range: -30d
    query: |
        aggregation: true
        logsource:
            product: linux
            service: auth
        detection:
            selection:
                event.action: ssh_login
                event.outcome: failure
                tags|contains: so-grid-node
            filter:
                User|expand: '%User%'
            condition: selection and not filter
        fields:
            - source.ip
            - User
            - host.name
    example_query_output: '1 | 192.168.55.6 | sysadmin2 | sa-sensor02'
